"""Held-out experiment with researcher control removed from the episode state.

The harness gives Cognitia problems and a candidate set, but does not provide a
hypothesis identifier, an uncertainty label, an expected action, or a scenario-
specific action mapping. The training action is whatever the existing system
selects. A later problem is deliberately from a different domain and shares no
content-bearing problem terms with training.

The purpose is diagnostic: determine whether the current experience pathway
actually changes behavior on a novel problem when the researcher stops telling
it what matters. A failure is a result, not a test defect.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from cognitia.experience import (
    CognitiveState,
    EpistemicOutcome,
    ExpectedConsequence,
    Experience,
    ExperienceLedger,
    ObservedConsequence,
)
from cognitia.experience_decision import ExperienceAwareActionSelector
from cognitia.research_search import ResearchSearchPlanner, SearchAction


TRAIN = "Why did the payment queue stall after a database outage?"
HELD_OUT = "Why did the telescope image degrade after a mirror coating changed?"
ROLE_REVERSAL = "Why did the database outage cause the payment queue to stall?"
_STOPWORDS = {"why", "did", "the", "after", "a", "what", "caused", "to", "and", "of", "in", "on", "for", "is", "was"}


def candidate_actions(problem: str) -> list[SearchAction]:
    planned = list(ResearchSearchPlanner().plan(problem, max_actions=4).actions)
    return list(reversed(planned))


def content_terms(value: str) -> set[str]:
    return {term for term in re.findall(r"[a-z0-9]+", value.lower()) if len(term) > 2 and term not in _STOPWORDS}


def select(problem: str, ledger: ExperienceLedger) -> dict[str, object]:
    candidates = candidate_actions(problem)
    decision = ExperienceAwareActionSelector().select(problem, candidates, ledger)
    return {
        "problem": problem,
        "candidate_order": [item.query.objective for item in candidates],
        "selected": decision.selected.action.query.objective,
        "selected_purpose": decision.selected.action.purpose,
        "ranked": [
            {
                "objective": item.action.query.objective,
                "score": item.score,
                "relevant_experience_ids": list(item.relevant_experience_ids),
            }
            for item in decision.candidates
        ],
    }


def generated_experience(problem: str, selected_objective: str) -> Experience:
    selected = next(item for item in candidate_actions(problem) if item.query.objective == selected_objective)
    return Experience(
        experience_id="system-generated-1",
        prior_state=CognitiveState(problem),
        action=selected.query.objective,
        rationale="Selected by Cognitia from its candidate action set.",
        expected=ExpectedConsequence("investigation attempted"),
        observed=ObservedConsequence(
            "investigation attempted",
            EpistemicOutcome.CONFIRMED,
            evidence_ids=("evidence:system-generated-1",),
        ),
        state_update=CognitiveState(problem),
        provenance=("no-handholding-v2",),
    )


def main() -> None:
    empty = ExperienceLedger()
    baseline_train = select(TRAIN, empty)
    experience = generated_experience(TRAIN, baseline_train["selected"])
    learned = ExperienceLedger((experience,))

    held_out_without = select(HELD_OUT, empty)
    held_out_with = select(HELD_OUT, learned)
    role_reversal_with = select(ROLE_REVERSAL, learned)

    train_terms = content_terms(TRAIN)
    held_out_terms = content_terms(HELD_OUT)

    artifact = {
        "experiment": "held-out-no-handholding-v2",
        "research_question": "When researcher guidance is removed and the held-out problem changes domain, does experience generated by Cognitia itself alter later action selection?",
        "records": {
            "training": baseline_train,
            "held_out_without_experience": held_out_without,
            "held_out_with_experience": held_out_with,
            "role_reversal_with_experience": role_reversal_with,
            "generated_experience": {
                "experience_id": experience.experience_id,
                "action": experience.action,
                "prior_state_has_hypothesis_ids": bool(experience.prior_state.hypothesis_ids),
                "prior_state_has_uncertainty": bool(experience.prior_state.uncertainty),
                "provenance": list(experience.provenance),
            },
        },
        "observations": {
            "experience_changes_held_out_selection": held_out_without["selected"] != held_out_with["selected"],
            "held_out_has_zero_content_term_overlap": not (train_terms & held_out_terms),
            "held_out_shared_content_terms": sorted(train_terms & held_out_terms),
            "experience_is_considered_relevant_by_current_selector": bool(held_out_with["ranked"][0]["relevant_experience_ids"]),
            "role_reversal_differs_from_training": role_reversal_with["selected"] != baseline_train["selected"],
            "candidate_order_was_reversed": True,
        },
        "researcher_controls_removed": [
            "no expected action",
            "no hypothesis identifiers",
            "no uncertainty labels",
            "training action comes from Cognitia's own selector",
            "candidate order is reversed",
            "held-out problem uses a different domain and no shared content-bearing terms",
            "role-reversal case is observed rather than assigned a required answer",
        ],
        "interpretation_boundary": "A changed or unchanged selection is evidence about the current explicit experience-to-action mechanism only. It does not establish cognition, semantic understanding, or learning.",
        "next_discriminator": "Replace lexical experience relevance with the structured relation/event representation already produced by the language layer, then repeat this same no-handholding protocol without adding scenario-specific routing.",
    }
    output = Path(".ci/held-out-no-handholding-v2.json")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(artifact, indent=2, sort_keys=True), encoding="utf-8")
    print(json.dumps(artifact, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
